### PR TITLE
add Node.js 10 LTS dubnium

### PR DESCRIPTION
**Pull request by richardlau**
Refs: https://github.com/nodejs/node/pull/23831#issuecomment-434422816

### CODE REVIEW

**Comment by richardlau** [comment]
cc @nodejs/build

**Comment by MylesBorins** [comment]
@nodejs/build what needs to be done to make this work?

**Comment by knksmith57** [comment]
after chasing around shell script call sites and previous GH issues, I _think_ this is how it works:
1. when ansible bootstraps the build (and also web, and docs, and maybe _everything_?) instance, it globally installs `nodejs-latest-linker`
  * https://github.com/nodejs/build/blob/f48fc38/setup/www/tasks/tools.yaml#L6
2. linker is called by `promote_release.sh` which is intended to be called by `dist-promote` on an ad-hoc basis by the release manager
  * https://github.com/nodejs/build/blob/f48fc38/setup/www/tools/promote/promote_release.sh#L27
  * https://github.com/nodejs/build/blob/f48fc38/setup/www/tools/dist/dist-promote#L17
  * https://github.com/nodejs/build/blob/f48fc38/setup/www/tools/promote/README.md

Because the package is globally installed _once_ and, unless I'm missing a scheduled updater somewhere, not upgraded again automatically, I _think_ a release manager needs to shell onto the instance and bump the global install (or maybe re-run the playbook?).

It looks like Rod did something similar when Carbon was released: https://github.com/nodejs/nodejs-latest-linker/pull/1#issuecomment-341577328.

Definitely interested to hear from the build WG --at a minimum we could probably prefer to `npx <pkg>` for the globally-installed node deps to prevent this sort of manual intervention / version bumping.

**Comment by rvagg** [comment]
nicely deduced @knksmith57!

Getting this deployed and updated now. Unfortunately `npx` doesn't really solve the problem because the big hurdle is right here, getting the change in, merged and published. It's trivial for someone with publish access to also update on the server.

What might be a more interesting solution is for an update to nodejs-latest-linker that pulls down https://github.com/nodejs/Release/blob/master/schedule.json and uses that rather than having to take manual updates. Then there's not even an update required here.

**Comment by rvagg** [comment]
https://nodejs.org/download/release/latest-dubnium/ all done

**Comment by knksmith57** [comment]
ah, that makes sense --it didn't occur to me that most (all?) devs w/ publish perms for this package would also have shell access to the box.

thanks for following up and for handling the rollout 🙏

**Comment by knksmith57** [comment]
also, heads up @rvagg: looks like there's a cyclical symlink to `v10.13.0` in the `/download/release/latest-dubnium` dir that we may want to prune --possibly an artifact from @MylesBorins's ad-hoc linkage last night. Probably not a big deal but certainly unnecessary.

eg: https://nodejs.org/download/release/latest-dubnium/v10.13.0/v10.13.0/v10.13.0/v10.13.0/v10.13.0/v10.13.0/v10.13.0/v10.13.0/v10.13.0/

**Comment by MylesBorins** [comment]
Cyclical symlink should be gone now 😇

**Pull request merged**
